### ISSUE TITLE
Really love your UI Kit . Would love proper docs like Bulma.io along with examples.

### ISSUE THREAD

**Issue by highoncarbs** [Aotik/Blossom#4]
Improve documentation.

**Comment by animify** [comment]
Thank you! Have you visited https://getblossom.io ? You can find example snippets, helper classes & more there. Or do you mean to expand the site further with more docs?

**Comment by highoncarbs** [comment]
Yep. More docs , also it would be great if you could add helper functions like bulma does.
It would be great to work on this !

**Comment by animify** [comment]
Fair enough, I'll take a look at how I could make the docs more efficient when I get some free time! Appreciate the feedback

**Comment by highoncarbs** [comment]
Thanks for the work !
