### ISSUE TITLE
Arrow icons on accordion not displaying

### ISSUE THREAD

**Issue by ThatTonybo** [Aotik/Blossom#5]
The arrows that animate on click on the [accordion](https://getblossom.io/elements/accordion) component aren't displaying in any local projects, yet seem to display on the official website.

Is this a known/fix-planned bug?

**Comment by ThatTonybo** [comment]
Got a picture using the default example:

![image](https://user-images.githubusercontent.com/28176227/47000112-e8f66300-d16a-11e8-8b62-2da8c5220aaf.png)

**Comment by animify** [comment]
Hey! So the arrows shown in the Accordion is the based off the Ionicons icon font. If you head over to https://ionicons.com/ and include the icon CSS stylesheet on your site you should be good to go
