### ISSUE TITLE
Website is gone, download CDN is dead

### ISSUE THREAD

**Issue by ThatTonybo** [Aotik/Blossom#6]
![image](https://user-images.githubusercontent.com/28176227/59069880-09db1680-88fc-11e9-92c0-29cdb0c51125.png)

It seems the website is now down, and the darken CDN with the Blossom download has gone too. What's happening?

Blossom is my favorite, so if I could also build the documentation myself, it'd be appreciated.

**Comment by animify** [comment]
Hey! You're right, there was an issue with the DNS after I migrated servers. Weird!

Whilst that's updating, feel free to check out https://blossom-styleguide.netlify.com (download should be working fine there as well).

Glad you like Blossom!

**Comment by ThatTonybo** [comment]
Awesome, thank you!
